language: node_js
node_js:
  - "8"

dist: trusty                  # 指定系统版本，trusty 是指 Ubuntu 14.04 发行版的名称
sudo: required                # 是否需要 sudo 权限
 
before_script:
 - npm install
  
script:
 - npm run build


after_script:
  - cd ./dist
  - echo 'yong.zone' >CNAME
  - git init
  - git config user.name "yyf1994gggg"
  - git config user.email "602875520@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master


env:
 global:
   - GH_REF: github.com/yyf1994gggg/yyf1994gggg.github.io.git